export const startingPieces = [
  // white pieces
  { type: "rook" as const, color: "white" as const, rank: 1, file: "a" },
  { type: "knight" as const, color: "white" as const, rank: 1, file: "b" },
  { type: "bishop" as const, color: "white" as const, rank: 1, file: "c" },
  { type: "queen" as const, color: "white" as const, rank: 1, file: "d" },
  { type: "king" as const, color: "white" as const, rank: 1, file: "e" },
  { type: "bishop" as const, color: "white" as const, rank: 1, file: "f" },
  { type: "knight" as const, color: "white" as const, rank: 1, file: "g" },
  { type: "rook" as const, color: "white" as const, rank: 1, file: "h" },
  { type: "pawn" as const, color: "white" as const, rank: 2, file: "a" },
  { type: "pawn" as const, color: "white" as const, rank: 2, file: "b" },
  { type: "pawn" as const, color: "white" as const, rank: 2, file: "c" },
  { type: "pawn" as const, color: "white" as const, rank: 2, file: "d" },
  { type: "pawn" as const, color: "white" as const, rank: 2, file: "e" },
  { type: "pawn" as const, color: "white" as const, rank: 2, file: "f" },
  { type: "pawn" as const, color: "white" as const, rank: 2, file: "g" },
  { type: "pawn" as const, color: "white" as const, rank: 2, file: "h" },
  // black pieces
  { type: "rook" as const, color: "black" as const, rank: 8, file: "a" },
  { type: "knight" as const, color: "black" as const, rank: 8, file: "b" },
  { type: "bishop" as const, color: "black" as const, rank: 8, file: "c" },
  { type: "queen" as const, color: "black" as const, rank: 8, file: "d" },
  { type: "king" as const, color: "black" as const, rank: 8, file: "e" },
  { type: "bishop" as const, color: "black" as const, rank: 8, file: "f" },
  { type: "knight" as const, color: "black" as const, rank: 8, file: "g" },
  { type: "rook" as const, color: "black" as const, rank: 8, file: "h" },
  { type: "pawn" as const, color: "black" as const, rank: 7, file: "a" },
  { type: "pawn" as const, color: "black" as const, rank: 7, file: "b" },
  { type: "pawn" as const, color: "black" as const, rank: 7, file: "c" },
  { type: "pawn" as const, color: "black" as const, rank: 7, file: "d" },
  { type: "pawn" as const, color: "black" as const, rank: 7, file: "e" },
  { type: "pawn" as const, color: "black" as const, rank: 7, file: "f" },
  { type: "pawn" as const, color: "black" as const, rank: 7, file: "g" },
  { type: "pawn" as const, color: "black" as const, rank: 7, file: "h" },
];
